### ISSUE TITLE
Goal: Pipeline Output UX

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#257]
As a user of the DCP, I expect the data that is in the DCP to be as standardized as possible so I can easily analyze it. This implies that the qc metrics that we output from our pipelines are all named the same if they are the same metric, and are organized and stored in expected ways. Our bams need to be consistent with the metadata in their headers and naming conventions, and our cell matrices need to be consistent in metadata that is included, col / row headers, just to name a few. The matrix service, unity, and the users depend on us to provide consistent outputs. 

ACs:
- [ ] A list of requirements for all outputs of all pipelines that run in the HCA DCP with small examples
- [ ] Our pipelines produce identically formatted outputs wherever possible and meet those requirements
- [ ] Validation tools that confirm that outputs meet that spec that would work for us in development, can be expanded on easily, could be used by others in EE, and can be run by ingestion on the outputs coming out of our pipelines. Can be used in CI compliance tests.
- [ ] Documentation on all of these validation tools

See an initial spike into this work on our QC outputs [here](https://github.com/HumanCellAtlas/skylab-analysis/blob/master/analyses/metrics/determine_qc_metric_schema.ipynb)

Ideas from that work:
- [ ] Create a metrics package that through modularity and extensibility supports mapping future pipelines onto a common schema
- [ ] Allow exchange of output format types, to support changes in downstream file type requests
- [ ] Expose converters for multiple input types

~~Old notes:
Pre Nov 1 tickets: #105 > #77 > #290 > #288 
Soon after that: #291 > #251 > #289 > #292
Can be done in parallel anytime after #290: #77 improve content of expression matrix for SS2~~

┆Issue is synchronized with this [Jira Bug](https://broadinstitute.atlassian.net/browse/GL-521)

**Comment by ambrosejcarr** [comment]
Nice, LGTM.

**Comment by kbergin** [comment]
https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md

A suggestion for a spec model, also some parts of this may be useful to put into our own spec.
