### ISSUE TITLE
Acceptance Report for Optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#410]
An epic to group the tickets to report on .

- [ ] Requested information on current status of Optimus - what is in the pipeline now, demo of pipeline
- [ ] Requested focus on delivering comparison of Optimus to cellranger v3 (not 2)

Plan: https://docs.google.com/document/d/1V1vjgXhfVkeybsZA80Td5iul5nuxGvXKY3b6w2c_yiU/edit#

ACs:
- [ ] Optimus report on comparison to Cellranger v3
- [ ] Meets expectations of AWG surrounding EmptyDrops, Chimeric Reads, and analysis report content
