### ISSUE TITLE
HCA DCP Users can download Expression Matrices for 10x v2 analyses

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#486]
See [One Pager](https://docs.google.com/document/d/1eOpTZBnQuMwn-tv704xnW4aai-hJc42AfE5kibRLrCQ/edit?ts=5bd98b32#) or Goal Epic for Motivation.

## Acceptance Criteria
- [x] Optimus runs on notification from the DCP Data Store in Production
- [x] Optimus is run in standard integration and mintegration tests
- [x] Optimus can be monitored in Job Manager UI
- [x] Outputs from the Optimus pipeline can be observed in the Data Browser and accessed by the Matrix Service
- [x] Cost and timing are monitored by a regular script
- [x] User facing documentation is published on the HCA data portal.
- [x] Appropriate 10X datasets are reanalyzed (There are four possible datasets as of Jan 3, one is blocked.)
