### ISSUE TITLE
Optimus has functionally equivalent features with Cellranger Count v3 and one improvement

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#487]
### Create an MVP of Optimus pipeline with known feature requirements and bug fixes. 
1. What problem? Approximately 50% of the datasets currently residing in the HCA DCP are of this data type. The current pipeline we have run as a placeholder is not ideal for cloud processing, not extensible to other data types, not reliably open source (a requirement of ours), and is brittle. The modularity and flexibility of the Optimus pipeline enables us to better support the needs of the HCA community surrounding this data type.
2. Why does it support our OKRs? This will help us meet O1 by allowing us to analyze a new data type and creating an extensible base pipeline that will enable an easier addition of other future data types. 
3. UX: A user at this point would be able to run the pipeline in Terra or on their own.

### Acceptance Criteria
- [ ] Tagging a v1.0 of the pipeline in Skylab and dockers are appropriately tagged.
- [ ] Readme is updated with appropriate information
- [x] Outputs are optionally available in zarr format and in the standard output format.
- [x] Emptydrops is included as a feature.
- [ ] No requirements currently on cost or runtime.
- [ ] Tested in PR tests and guidance on testing this in integration including testing data is provided or documented.
- [ ] V1.0 of Optimus Pipeline is published in Terra and Dockstore with example inputs / test data.
- [ ] Documented list of inputs and outputs is compiled and example inputs, dependencies, and outputs are provided alongside pipeline and in a document or readme.

Please note that given this epic is being created when most of the pipeline is already done, the acceptance criteria are a bit more vague or not written down for work that is already done, like creating a metrics suite or generating the other features of the pipeline that enable equivalency.
