### ISSUE TITLE
Pipeline Testing

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#511]
As we write pipelines we will want to be able to easily test them as we make updates to them. Brainstorming on 1/30 to come up with a testing plan.

[Previous document on testing Optimus](https://docs.google.com/document/d/1_CHHEEWOySB-cgzYSRUh-CsYBobNT0Uhsabi4zmiUuM/edit#heading=h.t2ki2gy37f86)

- [ ] Regular scientific testing
- [ ] Plumbing tests (for integration and PRs)
- [ ] Complete benchmarking suite
- [ ] Any others? 

Eventually we'll want output compliance tests but I don't think we're there yet.
