### ISSUE TITLE
UMI correction improvement for MVP

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#521]
A few reasons to remove UmiAwareMarkDuplicates: It's extremely slow on our data type, it's not tested for our data type, and it's not actually performing the task it was going to do correctly anyways.

> First, it is extremely computationally intensive. Second it heavily relies on the position of the read (as opposed to the transcript of origin). This is problematic for protocols, like 10X, where the fragmentation occurs after amplification. Finally, CBs are not fully leveraged.

AC:
- [x] Choose a tool that properly completes this step
- [ ] Implement in WDL
- [ ] Implement in pipeline
- [ ] Benchmark pipeline for final acceptance report
- [ ] Update documentation and testing

**Comment by barkasn** [comment]
Capturing information about umi-tools and feasibility of integrating into optimus:

* UMI-tools has two relevant commands _dedup_ and _group_. _dedup_ removes reads, whereas group appends a readgroup in an read group field. This is _not_ the same as the bam specification read group (the @RG header line that uses RG tags, by default umi-tools uses UG=read group id, BX=read group id)

* UMI-tools by default expects the UMI to be in the read name (appended after an underscore), but it can read it from any bam file tag specified by the user. The relevant options are --extract-umi-method tag --umi-tag XX --cell-tag XX and seem to be supported by both dedup and group.

Therefore it should be very strait-forward to add umi-tools to the pipeline should we wish.
