### ISSUE TITLE
Support Mouse data in HCA

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#747]
As a user of the HCA, I want to have access to processed data for mouse. Currently there are 3 datasets (one is very large) of mouse data in the HCA that we could process if we had a mouse reference for our SS2 and Optimus pipelines.

The DCP governance group has agreed to include 'mouse atlas' data in the HCA DCP as it provides such a valuable resource to the community. Any mouse data that matches a pipeline we run we will need to run a corresponding mouse version of the pipeline.

AC:
Pipelines are run off subscription in the green box with a mouse reference

Progress checklist:
- [X] Mouse reference generated for SS2 and is released
- [ ] Mouse SS2 is validated scientifically and has a test
- [x] Example bundles for SS2 exist in the integration DCP
- [X] Mouse SS2 is hooked up to the infrastructure
- [ ] SS2 Mouse is released to Production
- [ ] Mouse SS2 data in Prod is analyzed

┆Issue is synchronized with this [Jira Epic](https://broadinstitute.atlassian.net/browse/GL-236)

**Comment by kbergin** [comment]
Team doc on work, including work notes. https://docs.google.com/document/d/1lgyFTErSnS58zpefmXTris04UKEOzEwVPkIEeoGfIew/edit#heading=h.rg7fctozbba ( https://docs.google.com/document/d/1lgyFTErSnS58zpefmXTris04UKEOzEwVPkIEeoGfIew/edit#heading=h.rg7fctozbba )

**Comment by kbergin** [comment]
Reopened to cover remaining infrastructure work which has been added into this Epic
