### ISSUE TITLE
Goal: Optimus MVP

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#86]
### KR1: Optimus v1 is a featured method in Terra (yes/no)
Hypothesis: If the MVP of Optimus pipeline is completed and benchmarked, we can highlight it to the community by featuring it in Terra. Relies on Brad and Rob M to get featured, they are aware of dependency and timeline.
### KR2: Process 4 10xv2 datasets in HCA DCP in Production using Optimus given they are available.
Hypothesis: If the MVP of the Optimus pipeline is completed, it can be implemented in the HCA infrastructure and used to process production data. 
### KR3: Users can download expression matrices for at least 5 datasets in the HCA
Current status: Users can download matrices through the service for 2 (SmartSeq2) datasets.
Hypothesis: If the Optimus pipeline is used to analyze HCA 10x Data and the outputs include a zarr gene expression matrix, then users can use the matrix service through the HCA Data Browser to have easy access to Optimus gene matrices.

## Acceptance Criteria
- [ ] Optimus is tagged and in firecloud methods repo and dockstore
- [ ] Plan for improvements to Optimus is outlined
- [ ] Documentation on Optimus is updated and available to users
- [ ] All 10x data is reanalyzed in prod with this pipeline. Ok to try running it in int or staging first.
- [ ] Outputs are in Zarr format for Matrix Service but also include another format of output
- [ ] Cost of pipeline runs is entered [here](https://docs.google.com/spreadsheets/d/1Y5CBCW-lIXhpWSIrQtrl9IhuyqlNyfHdC_mlVkFIfU0/edit#gid=0)

## More Information
See one pager on Optimus [here](https://docs.google.com/document/d/1eOpTZBnQuMwn-tv704xnW4aai-hJc42AfE5kibRLrCQ/edit?ts=5bd98b32#heading=h.ff2yp6ydu4n)

**Comment by kbergin** [comment]
We have a benchmarking test suite for SS2
Goal is to show that Optimus performs similarly to CellRanger on the same reference

Start with a spike doc to make a benchmarking plan to show to the AWG - including which datasets and which tests. - 34 for estimate

1) Jishu started an analysis for comparing Optimus on Gencode and Ensembl - need to complete this analysis. Compare using Optimus with same reference as SS2 (unfiltered)
2) Try using SS2 benchmarking suite on optimus/cellranger comparison - We have both the converted to zarr and original outputs.
      a) Compare QC metrics between CellRanger and Optimus on same ref
      b) Compare gene matrix between CellRanger and Optimus on same ref
